-- SmartCity Cloud: catálogo seguro de dispositivos y actuadores.
-- Ejecutar en Supabase > SQL Editor después de revisar el esquema.
-- Este script NO enciende hardware ni crea actuadores ficticios.
-- La API FastAPI debe validar el rol administrador antes de aceptar órdenes.

begin;

-- Verifica que las tablas actuales tengan las columnas necesarias.
do $$
begin
    if to_regclass('public.lecturas_sensores') is null then
        raise exception 'No existe public.lecturas_sensores.';
    end if;

    if not exists (
        select 1 from pg_attribute
        where attrelid = 'public.lecturas_sensores'::regclass
          and attname = 'sensor_id' and not attisdropped
    ) then
        raise exception 'Falta lecturas_sensores.sensor_id.';
    end if;

    if to_regclass('public.usuarios') is null then
        raise exception 'No existe public.usuarios.';
    end if;

    if not exists (
        select 1 from pg_attribute
        where attrelid = 'public.usuarios'::regclass
          and attname = 'id' and not attisdropped
    ) then
        raise exception 'Falta usuarios.id.';
    end if;
end
$$;

-- lecturas_sensores guarda muchas lecturas por sensor_id y por eso no sirve
-- como destino directo de una clave foránea. Este catálogo registra un sensor una vez.
create table if not exists public.dispositivos_iot (
    sensor_id varchar primary key check (btrim(sensor_id) <> ''),
    nombre text not null default 'Sensor sin nombre',
    ubicacion text,
    latitud double precision,
    longitud double precision,
    firmware_version text,
    intervalo_esperado_segundos integer not null default 300
        check (intervalo_esperado_segundos between 10 and 86400),
    activo boolean not null default true,
    observaciones text,
    creado_en timestamptz not null default now(),
    actualizado_en timestamptz not null default now(),
    constraint dispositivos_iot_coordenadas_validas check (
        (latitud is null and longitud is null)
        or (latitud between -90 and 90 and longitud between -180 and 180)
    )
);

comment on table public.dispositivos_iot is
    'Catálogo de ESP32/sensores; vincula lecturas históricas y actuadores por sensor_id.';

-- Registra en el catálogo los IDs ya presentes en las lecturas.
-- No inserta filas en actuadores; eso se hará al registrar hardware real.
insert into public.dispositivos_iot (sensor_id, nombre)
select distinct btrim(sensor_id::text), 'Dispositivo ' || btrim(sensor_id::text)
from public.lecturas_sensores
where sensor_id is not null
  and btrim(sensor_id::text) <> ''
on conflict (sensor_id) do nothing;

create table if not exists public.actuadores (
    id bigint generated by default as identity primary key,
    sensor_id varchar not null unique,
    nombre text not null,
    tipo text not null default 'luminaria'
        check (tipo in ('luminaria', 'rele', 'ventilador', 'bomba', 'otro')),

    -- Orden solicitada por el sistema y estado informado por el dispositivo.
    estado_deseado boolean not null default false,
    estado_reportado boolean,
    modo text not null default 'manual'
        check (modo in ('manual', 'auto')),
    activo boolean not null default true,

    creado_por integer references public.usuarios(id) on delete set null,
    actualizado_por integer references public.usuarios(id) on delete set null,
    ultimo_comando_en timestamptz,
    ultima_respuesta_en timestamptz,
    creado_en timestamptz not null default now(),
    actualizado_en timestamptz not null default now(),

    constraint actuadores_sensor_fk
        foreign key (sensor_id)
        references public.dispositivos_iot(sensor_id)
        on update cascade
        on delete restrict
);

comment on table public.actuadores is
    'Actuadores asociados a un dispositivo IoT. estado_reportado queda NULL hasta recibir confirmación del hardware.';
comment on column public.actuadores.estado_deseado is
    'Último estado solicitado por la aplicación; no confirma que el ESP32 lo haya aplicado.';
comment on column public.actuadores.estado_reportado is
    'Estado confirmado por el ESP32; NULL significa que aún no se recibió confirmación.';

create index if not exists idx_actuadores_activo
    on public.actuadores (activo);
create index if not exists idx_actuadores_actualizado_en_desc
    on public.actuadores (actualizado_en desc);

-- Mantiene actualizado el timestamp incluso si una consulta SQL no lo envía.
create or replace function public.actualizar_timestamp_actuadores()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
    new.actualizado_en := pg_catalog.now();
    return new;
end;
$$;

revoke all on function public.actualizar_timestamp_actuadores()
    from public, anon, authenticated;

drop trigger if exists trg_actuadores_actualizado_en on public.actuadores;
create trigger trg_actuadores_actualizado_en
before update on public.actuadores
for each row execute function public.actualizar_timestamp_actuadores();

-- El frontend actual habla con FastAPI usando JWT propio y DATABASE_URL.
-- No dar acceso directo a anon/authenticated: FastAPI deberá validar al admin.
alter table public.dispositivos_iot enable row level security;
alter table public.actuadores enable row level security;
revoke all on table public.dispositivos_iot from public, anon, authenticated;
revoke all on table public.actuadores from public, anon, authenticated;

commit;

-- Verificación manual, ejecutar después del bloque anterior:
-- select conname, pg_get_constraintdef(oid)
-- from pg_constraint
-- where conrelid = 'public.actuadores'::regclass;
--
-- select count(*) as actuadores_registrados from public.actuadores;
